# Generated by Django 2.1.5 on 2019-01-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(default=2, upload_to='photos/%y/%m/%d'),
            preserve_default=False,
        ),
    ]
